### PR TITLE
Add requirements.txt reference in readme

### PR DESCRIPTION
**Pull request by sfraint**
Add requirements.txt reference in readme

### CODE REVIEW

**Comment by saparikh** [comment]
The setup playbook already installs the python dependencies

**Comment by saparikh** [comment]
:LGTM:

**Comment by saparikh** [comment]
let's add `docker` to the requirements.txt file.

we can swap the order of setup to install pybatfish and requirements first, before issuing any docker commands. don't want to make users run `pip install -r requirements.txt`

**Comment by saparikh** [comment]
I made those changes in my branch. we can skip this PR and just take a look at that one

**Comment by sfraint** [comment]
Covered elsewhere

**Pull request closed without merging**
